
CREATE TABLE topicos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    mensagem TEXT NOT NULL,
    data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
    estado ENUM('ABERTO','FECHADO','RESOLVIDO') DEFAULT 'ABERTO',
    autor VARCHAR(255) NOT NULL,
    curso VARCHAR(255) NOT NULL
);
